version: '1.0'

services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: memvers
      MYSQL_USER: wheel
      MYSQL_PASSWORD: 12345678

  redis:
    image: redis:7.0
    ports:
      - 6379:6379