version: '3'

services:
  memvers-database:
    container_name: memvers-database
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678 # change this password
      MYSQL_DATABASE: memvers
      MYSQL_USER: wheel
      MYSQL_PASSWORD: 12345678 # change this password

  memvers-cacheserver:
    container_name: memvers-cacheserver
    image: redis:7.0
    ports:
      - 6379:6379